= SAÉ 3.01 2024-2025
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae3-01-template

////
// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------


TIP: Pensez à mettre à jour les infos dans ce fichier pour que les badges pointent sur les résultats effectifs de vos intégrations continue ou sur la bonne licence logicielle.

WARNING: Ce dépôt présente le projet à développer dans le cadre de la SAÉ 3.01 du BUT1 Informatique de l'IUT de Blagnac.


Ce fichier `README.adoc` (dont vous lisez sûrement le rendu HTML automatiquement effectué par GitHUb), fait partie du dépôt initial cloné à partir du lien GitHub classroom qui vous a été donné en cours (https://classroom.github.com/a/fePVlfpN).
Vous trouverez le dépôt "template" qui a servi de base ici : https://github.com/IUT-Blagnac/sae3-01-template. En complément du cours Moodle de la SAE 3.01 (cf. <<liensUtiles>>), ce dépôt template vous permet d'accéder à des exemples d'https://github.com/IUT-Blagnac/sae3-01-template/issues[issues], de https://github.com/IUT-Blagnac/sae3-01-template/releases[releases], ou d'autres artefacts à venir.
////

toc::[]

== Equipe

Projet réalisé par::

- link:https://github.com/boubast[BOUVET Bastien] -- Scrum Master / Développeur
- link:https://github.com/YolanBrun[BRUN Yolan] --  Rédacteur / Développeur
- link:https://github.com/leonardo-correiamendes[CORREIA MENDES Leonardo] -- Chef de projet / Développeur
- link:https://github.com/Diego-PB[PENICAUD-BERNAL Diego] -- Responsable base de donnée / Développeur
- link:https://github.com/DanerSharifi-FR[SHARIFI Daner] -- Responsable serveur web / Développeur
- link:https://github.com/Smogita[CRISTINI Aidan] -- Git Master / Développeur


Tuteur enseignant de l'équipe:: 

- link:https://github.com/rboulle[BOULLE Rémi] -- Product Owner


Tutrice enseignante de l'équipe:: 

- link:https://github.com/ependaries[PENDARIES Esther]

== Contexte général

### Sujet "Dashboard du département"

Les salles du 1er étage du département d’informatique sont équipées de capteurs AM107. Ces capteurs remontent des données de présence (via la valeur `activity`), de luminosité (en lux) et de niveau de CO2 sur un flux MQTT.

L’objectif du projet est de développer une interface web permettant de visualiser les données remontées par les capteurs, les stocker dans une base et d’avoir un historique. Le but est de donner un aperçu de l’occupation des salles et de pouvoir faire des statistiques.

Un plan SVG des salles est disponible.

Le **livrable attendu** est constitué :

- un site/application **fonctionnel** et déployable sous la forme d’un container avec docker.
- des sources du site ou de l’application développée
- d’une doc précise d’installation au format asciidoc (l’installation sera testée sur machine GNU/Linux)
- un README présentant le projet avec, au début, la composition du groupe (Noms, prénoms)

Insistons sur le fait qu’un critère essentiel est que le livrable soit fonctionnel et déployable facilement !

[[liensUtiles]]
=== Liens utiles

[cols="1,2,3,4,5",options="header"]
|===
| Date  | Version  | Nom              | Lien | Description
|  Sem.2 ( 06/01/25 - 12/01/25 ) |   | Cours Moodle     | https://webetud.iut-blagnac.fr/mod/resource/view.php?id=36226[Sujet SAE] | Sujet de la SAE, à retrouver sur Webetud
|     | 1er Sprint | Sprint / Backlog 1 | https://github.com/orgs/IUT-Blagnac/projects/300/views/1[Backlog et 1er Sprint] | 1er Sprint / Backlog du 1er Sprint, avec chaque User Story et tâches
|        | 1er Sprint | Documentation Utilisateur | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Doc_Utilisateur/Doc_Utilisateur1.md[Documentation Utilisateur] | Installation et présentation du docker avec ses fonctionnalités
|        | 1er Sprint | Documentation Technique | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Doc_Technique/Doc_Technique1.md[Documentation Technique] | Fonctionnement et fichiers clés du docker
|        | 1er Sprint | Bilan Sprint 1   | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Bilans/Bilan_Sprint1.md[Bilan Sprint 1] |Bilan du premier Sprint
|        | 1er Sprint | Prévision Sprint 2 | https://github.com/orgs/IUT-Blagnac/projects/302[Prévision Sprint 2] | Prévision du prochain Sprint (2) 
| Sem.3 ( 13/01/25 - 19/01/25 ) | 2ème Sprint | Sprint / Backlog 2 | https://github.com/orgs/IUT-Blagnac/projects/302[Sprint 2] | 2ème Sprint / Backlog du 2ème Sprint, avec chaque User Story et tâches
|         | 2ème Sprint | Cahier de tests |https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Cahier_de_Tests.md[Cahier de tests] | Cahier de tests
|         | 2ème Sprint | Documentation Utilisateur | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Doc_Utilisateur/Doc_Utilisateur2.md[Documentation Utilisateur]| Installation et présentation du docker avec ses fonctionnalités
|         | 2ème Sprint | Documentation Technique | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Doc_Technique/Doc_Technique2.md[Documentation Technique] | Fonctionnement et fichiers clés du docker
|         | 2ème Sprint | Bilan Sprint 2 | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Bilans/Bilan_Sprint2.md[Bilan Sprint 2] | Bilan du deuxième Sprint
|        | 2ème Sprint | Prévision Sprint 3 | https://github.com/orgs/IUT-Blagnac/projects/303[Prévision Sprint 3] | Prévision du prochain Sprint (3) 
| Sem.4 ( 20/01/25 - 26/01/25 )   | 3ème Sprint | Sprint / Backlog 3 |  https://github.com/orgs/IUT-Blagnac/projects/303[Sprint 3] | 3ème Sprint / Backlog du 3ème Sprint, avec chaque User Story et tâches
|          | 3ème Sprint |  Cahier de tests | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Cahier_de_Tests.md[Cahier de tests] | Cahier de tests
|         | 3ème Sprint | Documentation Utilisateur |  https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Doc_Utilisateur/Doc_Utilisateur3.md[Documentation Utilisateur] |  Installation et présentation du docker avec ses fonctionnalités
|       | 3ème Sprint  | Documentation Technique | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Doc_Technique/Doc_Technique3.md[Documentation Technique] | Fonctionnement et fichiers clés du docker
| | 3ème Sprint | Bilan Sprint 3 | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Bilans/Bilan_Sprint3.md[Bilan Sprint 3] | Bilan du troisième Sprint
|===

- Le https://webetud.iut-blagnac.fr/course/view.php?id=841[cours Moodle] sur la SAE
- Le dépôt https://github.com/IUT-Blagnac/sae3-01-template[template] qui sert de base à tous les dépôts étudiants.
- Le lien https://classroom.github.com/a/OUF7gxEa[classroom] si besoin.

TIP: Pensez à utiliser les salons Discord dédiés pour poser vos questions.

== Réalisations 

TIP: Mettez ici toutes les informations nécessaire à l'utilisation de votre dépôt (comment on installe votre application, où sont les docs, etc.)




=== Organisation Générale

Ce projet est organisé autour de plusieurs dossiers et fichiers pour structurer le développement et le déploiement d'une application utilisant Docker, une base de données TimescaleDB, un serveur web Nginx, et un backend PHP. Voici une description de la structure :

[source]
----
.
├── BD
│   ├── README.md
│   └── script.sql
├── README.adoc
├── WEB
│   ├── Dockerfile
│   ├── index.php
│   └── index_old.html
├── docker-compose.yml
├── docker_control.sh
├── images
│   └── README.md
└── nginx.conf
----

=== Détails des Répertoires et Fichiers

==== `BD`
- **Description** : Ce répertoire contient les fichiers liés à la base de données.
- **Fichiers principaux** :
  - `README.md` : Documentation sur la configuration et l'utilisation de la base de données.
  - `script.sql` : Script SQL pour initialiser les tables de notre base de donnée.

==== `WEB`
- **Description** : Ce répertoire contient les fichiers nécessaires au serveur web et au backend PHP.
- **Fichiers principaux** :
  - `Dockerfile` : Définit l'image Docker pour le conteneur PHP, incluant les extensions nécessaires (comme `pdo_pgsql`).
  - `index.php` : Page principale qui interagit avec la base de données et affiche les données de la table `membre`.

==== Racine du Projet
- **Fichiers et Répertoires Principaux** :
  - `docker-compose.yml` : Définit les services Docker (Nginx, PHP, TimescaleDB) et leur configuration.
  - `docker_control.sh` : Script Bash pour simplifier le démarrage et l'arrêt des conteneurs Docker.
  - `nginx.conf` : Configuration personnalisée pour le serveur Nginx, permettant la prise en charge des fichiers PHP.

==== `images`
- **Description** : Répertoire pour stocker des ressources supplémentaires, comme des fichiers d'images ou des exemples.
- **Fichiers principaux** :
  - `README.md` : Documentation associée à ce répertoire.

=== Guide pour les Contributeurs

1. **Cloner le Projet** :
   ```bash
   git clone <URL_DU_DEPOT>
   cd <NOM_DU_DEPOT>
   ```

2. **Configurer et Lancer les Conteneurs Docker** :
   ```bash
   ./docker_control.sh
   ```
   - Suivez les instructions pour démarrer ou arrêter les conteneurs.

3. **Développement Web** :
   - Modifiez les fichiers dans le répertoire `WEB` pour mettre à jour le backend ou le frontend.

4. **Base de Données** :
   - Modifiez le script SQL dans le répertoire `BD` pour mettre à jour la strucure de la base de données.

=== Notes
- Le fichier `docker_control.sh` simplifie la gestion des conteneurs.
- Assurez-vous que Docker et Docker Compose sont installés sur votre machine avant de démarrer le projet.


== Gestion de projet & Qualité

Chaque sprint (semaine) vous devrez livrer une nouvelle version de votre application (release).
Utilisez pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

De plus ce fichier `README.adoc` devra être à jour des informations suivantes :

- Version courante : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v0.1.2[v0.1.2]
- Lien vers la doc technique
- Lien vers la doc utilisateur
- Liste des (ou lien vers les) User Stories (ToDo/Ongoing/Done) et % restant
- Tests unitaires et plans de test
- Indicateurs de qualité du code (dette technique)
- ... tout autre élément que vous jugerez utiles pour démontrer la qualité de votre application

Voici un exemple d'évaluation :

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image"></iframe>
++++
endif::[]
