= SAÉ 3.01 2024-2025
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae3-01-template

////
// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------


TIP: Pensez à mettre à jour les infos dans ce fichier pour que les badges pointent sur les résultats effectifs de vos intégrations continue ou sur la bonne licence logicielle.

WARNING: Ce dépôt présente le projet à développer dans le cadre de la SAÉ 3.01 du BUT1 Informatique de l'IUT de Blagnac.


Ce fichier `README.adoc` (dont vous lisez sûrement le rendu HTML automatiquement effectué par GitHUb), fait partie du dépôt initial cloné à partir du lien GitHub classroom qui vous a été donné en cours (https://classroom.github.com/a/fePVlfpN).
Vous trouverez le dépôt "template" qui a servi de base ici : https://github.com/IUT-Blagnac/sae3-01-template. En complément du cours Moodle de la SAE 3.01 (cf. <<liensUtiles>>), ce dépôt template vous permet d'accéder à des exemples d'https://github.com/IUT-Blagnac/sae3-01-template/issues[issues], de https://github.com/IUT-Blagnac/sae3-01-template/releases[releases], ou d'autres artefacts à venir.
////

toc::[]

== Equipe

Projet réalisé par::

- link:https://github.com/boubast[BOUVET Bastien] -- Scrum Master / Développeur
- link:https://github.com/YolanBrun[BRUN Yolan] --  Rédacteur / Développeur
- link:https://github.com/leonardo-correiamendes[CORREIA MENDES Leonardo] -- Chef de projet / Développeur
- link:https://github.com/Diego-PB[PENICAUD-BERNAL Diego] -- Responsable base de donnée / Développeur
- link:https://github.com/DanerSharifi-FR[SHARIFI Daner] -- Responsable serveur web / Développeur
- link:https://github.com/Smogita[CRISTINI Aidan] -- Git Master / Développeur


Tuteur enseignant de l'équipe:: 

- link:https://github.com/rboulle[BOULLE Rémi] -- Product Owner


Tutrice enseignante de l'équipe:: 

- link:https://github.com/ependaries[PENDARIES Esther]

== Contexte général

TIP: Cette partie de votre `README.adoc` peut être supprimée ou mise ailleurs.

=== Dépôt initial

Ce dépôt initial a été créé pour que tous les groupes de 2ème année aient les mêmes informations de départ.

Vous y trouverez des fichiers qui peuvent être supprimés s'ils ne vous sont pas utiles :

- `.gitignore` => un fichier minimaliste des éléments à ne pas pousser en général sur vos dépôts (utiliser la commande `git add -f` pour forcer l'ajout d'un fichier Jar qui ne bougera plus, pour archive par exemple).
- `.github` => le répertoire qui contient des éléments de gestion de projet :
** `workflows` => le repertoire qui contient les actions à lancer à chaque push sur votre repo. 
*** `blank.yml` => un exemple bidon mais dont vous pourrez vérifier l’exécution correcte (1er tag)
** `ISSUE_TEMPLATE` => le repertoire qui contient quelques templates pour vos issues.
*** `us.yml` => Exemple de template pour les User Stories
*** `bug.yml` => Exemple de template pour les issues de bug report

TIP: Adaptez ces fichiers à votre projet et à votre organisation. Et inspirez-vous en pour en ajouter.

[[liensUtiles]]
=== Liens utiles

- Le https://webetud.iut-blagnac.fr/course/view.php?id=841[cours Moodle] sur la SAE
- Le dépôt https://github.com/IUT-Blagnac/sae3-01-template[template] qui sert de base à tous les dépôts étudiants.
- Le lien https://classroom.github.com/a/OUF7gxEa[classroom] si besoin.

TIP: Pensez à utiliser les salons Discord dédiés pour poser vos questions.

== Réalisations 

TIP: Mettez ici toutes les informations nécessaire à l'utilisation de votre dépôt (comment on installe votre application, où sont les docs, etc.)




=== Organisation Générale

Ce projet est organisé autour de plusieurs dossiers et fichiers pour structurer le développement et le déploiement d'une application utilisant Docker, une base de données TimescaleDB, un serveur web Nginx, et un backend PHP. Voici une description de la structure :

[source]
----
.
├── BD
│   ├── README.md
│   └── script.sql
├── README.adoc
├── WEB
│   ├── Dockerfile
│   ├── index.php
│   └── index_old.html
├── docker-compose.yml
├── docker_control.sh
├── images
│   └── README.md
└── nginx.conf
----

=== Détails des Répertoires et Fichiers

==== `BD`
- **Description** : Ce répertoire contient les fichiers liés à la base de données.
- **Fichiers principaux** :
  - `README.md` : Documentation sur la configuration et l'utilisation de la base de données.
  - `script.sql` : Script SQL pour initialiser les tables de notre base de donnée.

==== `WEB`
- **Description** : Ce répertoire contient les fichiers nécessaires au serveur web et au backend PHP.
- **Fichiers principaux** :
  - `Dockerfile` : Définit l'image Docker pour le conteneur PHP, incluant les extensions nécessaires (comme `pdo_pgsql`).
  - `index.php` : Page principale qui interagit avec la base de données et affiche les données de la table `membre`.

==== Racine du Projet
- **Fichiers et Répertoires Principaux** :
  - `docker-compose.yml` : Définit les services Docker (Nginx, PHP, TimescaleDB) et leur configuration.
  - `docker_control.sh` : Script Bash pour simplifier le démarrage et l'arrêt des conteneurs Docker.
  - `nginx.conf` : Configuration personnalisée pour le serveur Nginx, permettant la prise en charge des fichiers PHP.

==== `images`
- **Description** : Répertoire pour stocker des ressources supplémentaires, comme des fichiers d'images ou des exemples.
- **Fichiers principaux** :
  - `README.md` : Documentation associée à ce répertoire.

=== Guide pour les Contributeurs

1. **Cloner le Projet** :
   ```bash
   git clone <URL_DU_DEPOT>
   cd <NOM_DU_DEPOT>
   ```

2. **Configurer et Lancer les Conteneurs Docker** :
   ```bash
   ./docker_control.sh
   ```
   - Suivez les instructions pour démarrer ou arrêter les conteneurs.

3. **Développement Web** :
   - Modifiez les fichiers dans le répertoire `WEB` pour mettre à jour le backend ou le frontend.

4. **Base de Données** :
   - Modifiez le script SQL dans le répertoire `BD` pour mettre à jour la strucure de la base de données.

=== Notes
- Le fichier `docker_control.sh` simplifie la gestion des conteneurs.
- Assurez-vous que Docker et Docker Compose sont installés sur votre machine avant de démarrer le projet.


== Gestion de projet & Qualité

Chaque sprint (semaine) vous devrez livrer une nouvelle version de votre application (release).
Utilisez pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

De plus ce fichier `README.adoc` devra être à jour des informations suivantes :

[[liensUtiles]]
=== Liens utiles

[cols="1,2,3,4,5",options="header"]
|===
| Date  | Version  | Nom              | Lien | Description
|  Sem.2 (8/01 - 14/01 ) |   | Cours Moodle     | https://webetud.iut-blagnac.fr/course/view.php?id=920[cours Moodle sur la SAE] | Contient toute information concernant le sujet et l'organisation de notre dépôt
|     |  | Backlog Produit  | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04/issues[Backlog produit] | Vous trouverez les priorités, critères d’acceptabilité et évaluation de compléxité dans le premier commentaire de chaque User Story (Veuillez filtrer en choisissant le label User Stories)
|       | 1er Sprint  | Sprint 1 | https://github.com/orgs/IUT-Blagnac/projects/171[Sprint 1] | La colonne User Stories représente les User stories à développer durant le sprint
|        | 1er Sprint | Bilan Sprint 1   | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04/blob/master/Doc/Sprint%201/bilanSprint1.adoc[Bilan Sprint 1] | Le bilan du premier Sprint. Contient aussi la prévision du prochain https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04/blob/master/Doc/Sprint%201/bilanSprint1.adoc#2-prochain-sprint[Sprint] 
|        | 1er Sprint | Documentation Utilisateur | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04/blob/master/Doc/Sprint%201/DocUtilisateur.adoc[Documentation Utilisateur] | Montre comment installer l'application et la présente avec ses fonctionnalités
|        | 1er Sprint | Documentation Technique | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04/blob/master/Doc/Sprint%201/DocTechnique.adoc[Documentation Technique] | Montre le fonctionnement et les fichiers clés de l'application
| Sem.3 (15/01 - 21/01 )  |2ème Sprint   | Cahier de tests | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04/blob/master/Doc/Sprint%202/CahierDeTest.adoc[Cahier de tests] | Donne les différents tests que l'on a pu effectuer
|         | 2ème Sprint | Documentation Utilisateur |    https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04/blob/master/Doc/Sprint%202/DocUtilisateur.adoc[Documentation Utilisateur]| Montre comment installer l'application et la présente avec ses fonctionnalités
|         | 2ème Sprint | Documentation Technique | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04/blob/master/Doc/Sprint%202/DocTechnique.adoc[Documentation Technique] |  Montre le fonctionnement et les fichiers clés de l'application
|         | 2ème Sprint | Sprint 2 | https://github.com/orgs/IUT-Blagnac/projects/173[Sprint 2] | La colonne User Stories représente les User stories à développer durant le sprint
|         | 2ème Sprint | Bilan Sprint 2 | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04/blob/master/Doc/Sprint%202/BilanSprint2.adoc[Bilan Sprint 2] | Le bilan du deuxième Sprint
|        | 2ème Sprint | Prévision Sprint 3 | https://github.com/orgs/IUT-Blagnac/projects/174[Prévision Sprint 3] | Prévision du prochain Sprint (3) 
| Sem.4 (22/01 - 29/01       | 3ème Sprint | Sprint 3 |  https://github.com/orgs/IUT-Blagnac/projects/174[Sprint 3] | La colonne User Stories représente les User stories à développer durant le sprint
|                            | 3ème Sprint |  Cahier de tests |  https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04/blob/master/Doc/Sprint%203/CahierDeTest.adoc[Cahier de tests] | Donne les différents tests que l'on a pu effectuer
|                            | 3ème Sprint | Documentation Utilisateur |  https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04/blob/master/Doc/Sprint%203/DocUtilisateur.adoc[Documentation Utilisateur] |  Montre comment installer l'application et la présente avec ses fonctionnalités
|       | 3ème Sprint  | Documentation Technique | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04/blob/master/Doc/Sprint%203/DocTechnique.adoc[Documentation Technique] | Montre le fonctionnement et les fichiers clés de l'application
| | 3ème Sprint | Bilan Sprint 3 | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-23-24-LocURa-Equipe-3A04/blob/master/Doc/Sprint%203/BilanSprint3.adoc[Bilan Sprint 3] | Le bilan du troisième Sprint
|===

- Version courante : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v0.1.2[v0.1.2]
- Lien vers la doc technique
- Lien vers la doc utilisateur
- Liste des (ou lien vers les) User Stories (ToDo/Ongoing/Done) et % restant
- Tests unitaires et plans de test
- Indicateurs de qualité du code (dette technique)
- ... tout autre élément que vous jugerez utiles pour démontrer la qualité de votre application

Voici un exemple d'évaluation :

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image"></iframe>
++++
endif::[]
