= SAÉ 3.01 2024-2025
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae3-01-template

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

toc::[]

== Equipe

Projet réalisé par::

- link:https://github.com/boubast[BOUVET Bastien] -- Scrum Master / Développeur
- link:https://github.com/YolanBrun[BRUN Yolan] --  Rédacteur / Développeur
- link:https://github.com/leonardo-correiamendes[CORREIA MENDES Leonardo] -- Chef de projet / Développeur
- link:https://github.com/Diego-PB[PENICAUD-BERNAL Diego] -- Responsable base de donnée / Développeur
- link:https://github.com/DanerSharifi-FR[SHARIFI Daner] -- Responsable serveur web / Développeur
- link:https://github.com/Smogita[CRISTINI Aidan] -- Git Master / Développeur

Tuteur enseignant de l'équipe:: 

- link:https://github.com/rboulle[BOULLE Rémi] -- Product Owner

Tutrice enseignante de l'équipe:: 

- link:https://github.com/ependaries[PENDARIES Esther]

== Contexte général

### Sujet "Dashboard du département"

Les salles du 1er étage du département d’informatique sont équipées de capteurs AM107. Ces capteurs remontent des données de présence (via la valeur `activity`), de luminosité (en lux) et de niveau de CO2 sur un flux MQTT.

L’objectif du projet est de développer une interface web permettant de visualiser les données remontées par les capteurs, les stocker dans une base et d’avoir un historique. Le but est de donner un aperçu de l’occupation des salles et de pouvoir faire des statistiques.

Le **livrable attendu** est constitué :

- un site/application **fonctionnel** et déployable sous la forme d’un container avec docker.
- des sources du site ou de l’application développée
- d’une doc précise d’installation au format asciidoc (l’installation sera testée sur machine GNU/Linux)
- un README présentant le projet avec, au début, la composition du groupe (Noms, prénoms)

[[liensUtiles]]
=== Liens utiles

[cols="1,2,3,4,5",options="header"]
|===
| Date  | Version  | Nom              | Lien | Description
|  Sem.2 ( 06/01/25 - 12/01/25 ) |   | Sujet SAE    | https://webetud.iut-blagnac.fr/mod/resource/view.php?id=36226[Sujet SAE] | Sujet de la SAE, à retrouver sur Webetud
|     | 1er Sprint | Sprint / Backlog 1 | https://github.com/orgs/IUT-Blagnac/projects/300/views/1[Backlog et 1er Sprint] | 1er Sprint / Backlog du 1er Sprint, avec chaque User Story et tâches
|        | 1er Sprint | Documentation Utilisateur | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Documentation/Doc_Utilisateur/Doc_Utilisateur1.md[Documentation Utilisateur] | Installation et présentation du docker avec ses fonctionnalités
|        | 1er Sprint | Documentation Technique | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Documentation/Doc_Technique/Doc_Technique1.md[Documentation Technique] | Fonctionnement et fichiers clés du docker
|        | 1er Sprint | Bilan Sprint 1   | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Documentation/Bilans/Bilan_Sprint1.md[Bilan Sprint 1] |Bilan du premier Sprint
|        | 1er Sprint | Prévision Sprint 2 | https://github.com/orgs/IUT-Blagnac/projects/302[Prévision Sprint 2] | Prévision du prochain Sprint (2) 
| Sem.3 ( 13/01/25 - 19/01/25 ) | 2ème Sprint | Sprint / Backlog 2 | https://github.com/orgs/IUT-Blagnac/projects/302[Sprint 2] | 2ème Sprint / Backlog du 2ème Sprint, avec chaque User Story et tâches
|         | 2ème Sprint | Cahier de tests |https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Documentation/Cahier_de_Tests.md[Cahier de tests] | Cahier de tests
|         | 2ème Sprint | Documentation Utilisateur | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Documentation/Doc_Utilisateur/Doc_Utilisateur2.md[Documentation Utilisateur]| Installation et présentation du docker avec ses fonctionnalités
|         | 2ème Sprint | Documentation Technique | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Documentation/Doc_Technique/Doc_Technique2.md[Documentation Technique] | Fonctionnement et fichiers clés du docker
|         | 2ème Sprint | Bilan Sprint 2 | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Documentation/Bilans/Bilan_Sprint2.md[Bilan Sprint 2] | Bilan du deuxième Sprint
|        | 2ème Sprint | Prévision Sprint 3 | https://github.com/orgs/IUT-Blagnac/projects/303[Prévision Sprint 3] | Prévision du prochain Sprint (3) 
| Sem.4 ( 20/01/25 - 26/01/25 )   | 3ème Sprint | Sprint / Backlog 3 |  https://github.com/orgs/IUT-Blagnac/projects/303[Sprint 3] | 3ème Sprint / Backlog du 3ème Sprint, avec chaque User Story et tâches
|          | 3ème Sprint |  Cahier de tests | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Documentation/Cahier_de_Tests.md[Cahier de tests] | Cahier de tests
|         | 3ème Sprint | Documentation Utilisateur |  https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Documentation/Doc_Utilisateur/Doc_Utilisateur3.md[Documentation Utilisateur] |  Installation et présentation du docker avec ses fonctionnalités
|       | 3ème Sprint  | Documentation Technique | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Documentation/Doc_Technique/Doc_Technique3.md[Documentation Technique] | Fonctionnement et fichiers clés du docker
| | 3ème Sprint | Bilan Sprint 3 | https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01/blob/master/Documentation/Bilans/Bilan_Sprint3.md[Bilan Sprint 3] | Bilan du troisième Sprint
|===



== Réalisations 

=== Organisation Générale

Ce projet est organisé autour de plusieurs dossiers et fichiers pour structurer le développement, le déploiement et la documentation d'une application complète. L'application utilise Docker, une base de données TimescaleDB, un serveur web Nginx, un backend PHP, ainsi que Node-RED pour gérer un flux MQTT. Voici une description de la structure actuelle :

[source]
----
  .
  ├── BD
  │   ├── README.md                      // Documentation de la base de données
  │   ├── diagramme_de_classe_bd.plantuml // Diagramme de classe de la base de données
  │   └── script.sql                     // Script SQL pour créer et initialiser la base de données
  ├── Docker
  │   ├── README.md                      // Documentation des conteneurs Docker
  │   ├── docker-compose.yml             // Configuration Docker Compose
  │   ├── nginx.conf                     // Configuration Nginx pour le serveur web
  │   ├── nodered                        // Configuration et données de Node-RED
  │   │   ├── flows.json                 // Flux Node-RED pour gérer les données
  │   │   └── settings.js                // Configuration Node-RED
  ├── Documentation
  │   ├── Bilans                         // Rapports des bilans de chaque sprint
  │   │   ├── Bilan_Sprint1.md
  │   │   ├── Bilan_Sprint2.md
  │   │   └── Bilan_Sprint3.md
  │   ├── Doc_Technique                  // Documentation technique détaillant les aspects techniques
  │   │   ├── Doc_Technique1.md
  │   │   ├── Doc_Technique2.md
  │   │   └── Doc_Technique3.md
  │   ├── Doc_Utilisateur                // Documentation utilisateur pour comprendre l'application
  │   │   ├── Doc_Utilisateur1.md
  │   │   ├── Doc_Utilisateur2.md
  │   │   └── Doc_Utilisateur3.md
  │   └── Cahier_de_Tests.md             // Cahier de tests pour valider les fonctionnalités
  ├── Reunions
  │   └── Reunion_1.md                   // Notes des réunions pour le suivi du projet
  ├── WEB
  │   ├── Dockerfile                     // Dockerfile pour le backend PHP
  │   ├── index.php                      // Page principale de l'application web
  │   ├── includes                       // Scripts PHP supplémentaires
  │   │   └── connexion.inc.php          // Gestion de la connexion à la base de données
  │   ├── assets                         // Ressources front-end (CSS, JS, images)
  │   │   ├── css
  │   │   ├── js
  │   │   └── images
  │   └── room.php                       // Page spécifique pour visualiser les données des salles
  ├── images
  │   ├── README.md                      // Documentation des images du projet
  │   └── diagramme_de_classe.png        // Diagramme de classe pour l'application
  ├── README.adoc                        // Document principal expliquant le projet
  └── docker_control.sh                  // Script pour gérer facilement les conteneurs Docker
----

=== Description des Composants

- **BD** : Contient tous les fichiers liés à la base de données, y compris les scripts SQL pour initialiser les tables et le diagramme UML.
- **Docker** : Regroupe les configurations Docker (Nginx, Node-RED, TimescaleDB) et les fichiers associés pour déployer l'application via des conteneurs.
- **Documentation** : Centralise toutes les documentations liées au projet, y compris les bilans, les guides utilisateur et technique, et le cahier de tests.
- **Reunions** : Archive des comptes rendus de réunions pour le suivi des discussions et des décisions.
- **WEB** : Inclut le backend PHP, les ressources front-end, et les scripts supplémentaires pour l'application web.
- **images** : Contient des ressources visuelles comme des diagrammes et des illustrations.

Ce projet offre une architecture modulaire pour simplifier le développement, la maintenance et le déploiement. Les conteneurs Docker permettent de gérer efficacement les services essentiels tels que la base de données, le serveur web et les flux MQTT avec Node-RED.

=== Guide pour les Contributeurs

1. **Cloner le Projet** :
   ```bash
   git clone https://github.com/IUT-Blagnac/SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01.git
   cd SAE-ALT-S3-Dev-24-25-Dashboard_du_departement-Equipe-3A01
   ```

2. **Lancer les Conteneurs Docker** :
   ```bash
   ./docker_control.sh
   ```
   - Suivez les instructions pour démarrer ou arrêter les conteneurs.

3. **Développement Web** :
   - Modifiez les fichiers dans le répertoire `WEB` pour mettre à jour le backend ou le frontend.

4. **Base de Données** :
   - Modifiez le script SQL dans le répertoire `BD` pour mettre à jour la strucure de la base de données.

=== Notes
- Le fichier `docker_control.sh` simplifie la gestion des conteneurs.
- Assurez-vous que Docker et Docker Compose sont installés sur votre machine avant de démarrer le projet.


== Gestion de projet & Qualité

Chaque sprint (semaine) vous devrez livrer une nouvelle version de votre application (release).
Utilisez pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

De plus ce fichier `README.adoc` devra être à jour des informations suivantes :

- Version courante : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v0.1.2[v0.1.2]
- Lien vers la doc technique
- Lien vers la doc utilisateur
- Liste des (ou lien vers les) User Stories (ToDo/Ongoing/Done) et % restant
- Tests unitaires et plans de test
- Indicateurs de qualité du code (dette technique)
- ... tout autre élément que vous jugerez utiles pour démontrer la qualité de votre application

Voici un exemple d'évaluation :

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image"></iframe>
++++
endif::[]
